import { inter } from "@/common/fonts";
import { ColorSchemeScript } from "@mantine/core";
import type { Metadata } from "next";
import { Providers } from "./providers";

// 1. mantine ui stylesheet
import "@mantine/core/styles.css";

// 2. tailwindcss stylesshieet
import "@/tailwind.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
