name: Build Test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - name: Cache node_modules
        uses: actions/cache@v4
        id: node_modules_cache_id
        with:
         path: '**/node_modules'
         key: ${{ runner.os }}-build-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Install dependencies
        if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: pnpm install

      - name: Build application
        run: pnpm build
